#!/usr/bin/env bash

currentPerformanceYear=2018
# We assume we'll never need to rebuild measures for a previous
# performance year. If you need to rebuild measures
# for a previous performance year, you'll have to:
# 1. use the git history of this file
# 2. use the git history of any necessary import scripts
# 3. revert any changes to directory structures below.

quality_csv='../../../util/measures/'$currentPerformanceYear'/quality-measures.csv'
quality_strata='../../../util/measures/'$currentPerformanceYear'/quality-strata.csv'
quality_measures='../../../staging/'$currentPerformanceYear'/measures-data-quality.json'
# final_measures='../../measures/'$currentPerformanceYear'/measures-data.json'

# 0. Add quality measures to the staging measures-data-quality.json file:
node scripts/measures/$currentPerformanceYear/import-quality-measures.js \
	$quality_csv $quality_strata $quality_measures

# TODO: Enrich `measures-data.json` file, run:
# node scripts/measures/enrich-measures-data.js \
#	$staging_measures_with_qcdrs $final_measures
# For now, just copy the staging measures file over.
cat staging/$currentPerformanceYear/measures-data-quality.json > \
	measures/$currentPerformanceYear/measures-data.json

# 2. To regenerate the `measures-data.xml` file, run:
echo "generating measures-data.xml from measures-data.json"
cat measures/$currentPerformanceYear/measures-data.json | \
	node scripts/convert-json-to-xml.js \
		> measures/$currentPerformanceYear/measures-data.xml

# 3. Validate the resulting measures-data.json file:
echo "validating new measures-data.json"
cat measures/$currentPerformanceYear/measures-data.json | \
	node scripts/validate-data.js measures $currentPerformanceYear
