#!/usr/bin/env bash

# 0. Add QCDR measures to the 'staging/measures-data.json' file:
node scripts/measures/import-qcdr-measures.js

# 1. Enrich `measures-data.json` file, run:
node scripts/measures/enrich-measures-data.js

# 2. To regenerate the `measures-data.xml` file, run:
echo "generating measures-data.xml from measures-data.json"
cat measures/measures-data.json | node scripts/convert-json-to-xml.js > measures/measures-data.xml

# 3. Validate the resulting measures-data.json file:
echo "validating new measures-data.json"
cat measures/measures-data.json | node scripts/validate-data.js measures
