#!/usr/bin/env bash

# 1. Add QCDR measures to measures-data.json
# TODO(aimee) At the moment this is NOT idempontent
# jq -s add <(cat util/measures/2017-PIMMS-non-mips_measure_specifications.csv | node ./scripts/measures/import-csv.js util/measures/qcdr-config.yaml) measures/measures-data.json | tee measures/measures-data.json
jq -s '.[0] + .[1]' <(cat util/measures/2017-PIMMS-non-mips_measure_specifications.csv | node ./scripts/measures/import-csv.js util/measures/qcdr-config.yaml) measures/measures-data.json
# test cat measures/measures-data.json | wc -l should be >27354

# 2. Regenerate the `measures-data.xml` file:
echo "generating measures-data.xml from measures-data.json"
cat measures/measures-data.json | node scripts/convert-json-to-xml.js > measures/measures-data.xml

# 3. Validate the resulting measures-data.json file:
echo "validating new measures-data.json"
cat measures/measures-data.json | node scripts/validate-data.js measures
