#!/usr/bin/env bash

currentPerformanceYear=$(($1))
maxPerformanceYear=2026
categories=('ia' 'pi' 'cost' 'quality' 'qcdr')

Red='\033[0;31m'
Green='\033[0;32m'

# This script is not made to work for years prior to 2018.
if (( $currentPerformanceYear >= 2018 )) && (( $currentPerformanceYear <= $maxPerformanceYear )); then

  echo -e "Compiling Typescript..."
  tsc -p .

  echo -e "Converting to CSV..."
  mkdir -p tmp/
  mkdir -p tmp/$currentPerformanceYear
  for category in "${categories[@]}"
  do
    node dist/scripts/measures/json-to-csv.js \
      $currentPerformanceYear $category

  done
  
  echo -e "${Green}CSVs created: tmp/measures.csv"
  exit

else
  echo -e "${Red}Performance year ${currentPerformanceYear} not valid!"
fi
