#!/usr/bin/env bash
currentPerformanceYear=2023

# Update the measures-data, if there are any updates:
node scripts/measures/$currentPerformanceYear/update-measures.js \
	$currentPerformanceYear

echo "Ingesting the Spec Urls, if those files exist"
node scripts/measures/$currentPerformanceYear/ingest-links.js \
	$currentPerformanceYear

echo "Ingesting the benchmarks metadata"
node scripts/measures/$currentPerformanceYear/ingest-benchmark-metadata.js \
	$currentPerformanceYear

echo "validating new measures-data.json"
cat measures/$currentPerformanceYear/measures-data.json | \
	node scripts/validate-data.js measures $currentPerformanceYear