version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    allow:
      - dependency-name: "qpp*"
      - dependency-name: "@cmsgov/*"
    cooldown:
      default-days: 7
      exclude:
        - "@cmsgov/qpp-scoring-engines"
        - "qpp-measures-data"
        - "@cmsgov/qpp-shared-logger-node"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

