name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
replacers:
  - search: '/QPP([^\-]+)-(\d+)/gi'
    replace: '[QPP$1-$2](https://jira.cms.gov/browse/QPP$1-$2)'
change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES