name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
replacers:
  - search: '/QPPA-(\d+)/gi'
    replace: '[QPPA-$1](https://jira.cms.gov/browse/QPPA-$1)'
change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES