#!/usr/bin/env bash

currentPerformanceYear=$(($1))
maxPerformanceYear=2024

Red='\033[0;31m'
Green='\033[0;32m'

# This script is not made to work for years prior to 2023.
if (( $currentPerformanceYear >= 2023 )) && (( $currentPerformanceYear <= $maxPerformanceYear )); then

  echo -e "Compiling Typescript..."
  tsc -p .
  
  # Parse mvp data:
  echo -e "Parsing mvp-raw.json..."
  npm run parse:mvp $currentPerformanceYear

  # Update mvp-enriched, if there are any updates:
  echo -e "Updating mvp-enriched.json..."
  node dist/mvp/$currentPerformanceYear/update-mvp.js \
    $currentPerformanceYear
  
  echo -e "${Green}Update complete."
  exit

else
  echo -e "${Red}Performance year ${currentPerformanceYear} not valid!"
fi
