#!/usr/bin/env bash

currentPerformanceYear=2024

# compile TypeScript
tsc -p .

# generate EMA cluster data
echo "Generating clinical clusters:"
node dist/clinical-clusters/ema-clinical-cluster-builder.js $currentPerformanceYear util/clinical-clusters/$currentPerformanceYear/ClaimsClinical_Cluster.csv util/clinical-clusters/$currentPerformanceYear/RegistryClinicalCluster.csv

# validate EMA clusters
echo ""
echo "Validating clinical-clusters.json produced: "
node dist/validate-data.js clinical-clusters $currentPerformanceYear clinical-clusters/$currentPerformanceYear/clinical-clusters.json
