version: "2"
services:
  data-analysis:
    build: . 
    volumes:
      - ./:/home/jovyan/work:rw
      - ../measures/:/home/jovyan/measures:rw
      - ../:/home/:rw
    command: bash -c "start-notebook.sh --NotebookApp.token=''"
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/home/jovyan/work
