name: QPP Measures Release Notes Drafter
on:
  push:
    branches: [ release/* ]

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect and tag new version
        id: package-version
        uses: salsify/action-detect-and-tag-new-version@v2

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-draft.yml
          version: v${{ steps.package-version.outputs.current-version }}
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
