name: QPP Measures Data Feature PR CI/Checks
on: 
  pull_request:
    types: [opened, synchronize]
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Configure Node version and registry
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
