name: QPP Measures Data Feature PR CI/Checks
on:
  pull_request:
    types: [opened, synchronize]
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open beta version
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_NICHOLAS_PAT }}
        run: |
          echo "Fetching draft releases..."
          DRAFTS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${{ github.repository }}/releases \
                        | jq '.[] | select(.draft==true) | .tag_name')
        
          echo "Draft Releases IDs: $DRAFTS"
        
          for DRAFT_TAG in $DRAFTS; do
            if [ -n "$DRAFT_TAG" ]; then
            echo "$DRAFT_TAG"
            echo "${{ vars.LATEST_BETA_VERSION }}"
              if [ $DRAFT_TAG == '"${{ vars.LATEST_BETA_VERSION }}"' ]; then
                echo "Release Candidate in progress. Do not merge until the candidate is released, or force-merge to include in release."
                exit 1
              fi
            fi
          done
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Configure Node version and registry
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
