name: QPP Measures Data Publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure Node version and registry
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        if: ${{ !env.ACT }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  dump-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  # Make an announcement to other repositories of interest
  repo-dispatch:
    runs-on: ubuntu-latest
    needs: publish-npm
    strategy:
      matrix:
        repo:
          - CMSgov/qpp-scoring-engines
          - CMSgov/beneficiary-reporting-api
          - CMSgov/qpp-submissions-api
          - CMSgov/self-nomination-api
          - CMSgov/beneficiary-reporting-client
          - CMSgov/qpp-submission-client
          - CMSgov/claims-to-quality-analyzer
          - CMSgov/qpp-ui

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: lib-update-event
          client-payload: '{"ref": "${{ github.ref }}", "private_package": "@CMSGov/qpp-measures-data", "public_package":"qpp-measures-data" ,"tag_name": "${{ github.event.release.tag_name }}", "html_url": "${{github.event.release.html_url}}"}'

  # make an announcement to relevant slack channels
  notify-slack:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - name: Notify APP Submissions API Channel
        if: ${{ !env.ACT }}
        uses: rtCamp/action-slack-notify@96d5e2a64fc78a6b7ac13265f55bee296869967a #v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SUBMISSIONS_API_SLACK_WEBHOOK }}
          SLACK_CHANNEL: "p-qppsf-api"
          SLACK_MESSAGE: "`qpp-measures-data` has been updated to version <${{github.event.release.html_url}}|${{ github.event.release.tag_name }}>"
          SLACK_TITLE: New qpp-measures-data release
          SLACK_USERNAME: releaseNotify

  # create a backfill PR of master into develop
  backfill:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - name: Checkout Updated Master Branch
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create Pull Request
        if: ${{ !env.ACT }}
        id: pr
        uses: peter-evans/create-pull-request@45c510e1f68ba052e3cd911f661a799cfb9ba3a3 #v3.6.0
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          commit-message: Backfill develop with ${{ github.event.release.tag_name }}
          title: Backfill develop -  ${{github.event.release.tag_name}}
          branch: backfill_${{ github.event.release.tag_name }}
          base: develop
          body: |
            Auto generated pull request to backfill `${{ github.event.release.tag_name }} into develop`.
      - name: Notify APP Submissions API Channel of backfill PR
        if: ${{ !env.ACT }}
        uses: rtCamp/action-slack-notify@96d5e2a64fc78a6b7ac13265f55bee296869967a #v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SUBMISSIONS_API_SLACK_WEBHOOK }}
          SLACK_CHANNEL: "p-qppsf-api"
          SLACK_TITLE: ${{ github.event.release.tag_name }} backfill created
          SLACK_MESSAGE: "@qppa-devs - a backfill PR is awaiting verification https://github.com/CMSgov/qpp-measures-data/pull/${{steps.pr.outputs.pull-request-number}}"
          SLACK_USERNAME: prNotify
